name: dockerhub

on:
  push:
  schedule:
  - cron: "0 3 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push (Storm WS)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: stormproject/storm-ws:latest

    - name: Timestamp
      run: date --rfc-3339=seconds > last_build.txt

    - name: Commit and push
      uses: EndBug/add-and-commit@v7
      with:
        add: "last_build.txt"
        push: true
        committer_name: GitHub Actions
        committer_email: actions@github.com
